# Generated by Django 5.2.7 on 2025-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentariosmaquinas',
            fields=[
                ('idcomentariosmaquinas', models.AutoField(db_column='idComentariosMaquinas', primary_key=True, serialize=False)),
                ('comentario', models.TextField(db_column='Comentario')),
                ('fecharegistro', models.DateTimeField(db_column='FechaRegistro')),
                ('solucionado', models.IntegerField(db_column='Solucionado')),
            ],
            options={
                'db_table': 'comentariosmaquinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('area', models.CharField(db_column='Area', max_length=45)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=45)),
                ('estatus', models.IntegerField(db_column='Estatus')),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idlote', models.AutoField(db_column='idLote', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('fechatermtejido', models.DateTimeField(blank=True, db_column='FechaTermTejido', null=True)),
                ('fechatermplancha', models.DateTimeField(blank=True, db_column='FechaTermPlancha', null=True)),
                ('fechatermcorte', models.DateTimeField(blank=True, db_column='FechaTermCorte', null=True)),
                ('fechaempa', models.DateTimeField(blank=True, db_column='FechaEmpa', null=True)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('idmaquina', models.AutoField(db_column='idMaquina', primary_key=True, serialize=False)),
                ('area', models.CharField(db_column='Area', max_length=45)),
                ('numero', models.IntegerField(db_column='Numero')),
            ],
            options={
                'db_table': 'maquina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idmodelo', models.AutoField(db_column='idModelo', primary_key=True, serialize=False)),
                ('folio', models.CharField(db_column='Folio', max_length=45)),
                ('modelo', models.CharField(db_column='Modelo', max_length=45)),
                ('cantidadhilo', models.IntegerField(db_column='CantidadHilo')),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordendepedido',
            fields=[
                ('idordendepedido', models.AutoField(db_column='idOrdenDePedido', primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(db_column='FechaInicio')),
                ('fechafin', models.DateTimeField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'ordendepedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('talla', models.IntegerField(db_column='Talla')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('color', models.CharField(db_column='Color', max_length=45)),
                ('totallotes', models.IntegerField(db_column='TotalLotes')),
                ('loteterminado', models.IntegerField(db_column='LoteTerminado')),
                ('fechainicio', models.DateTimeField(db_column='FechaInicio')),
                ('fechafin', models.DateTimeField(db_column='FechaFin')),
                ('fechaprevista', models.DateTimeField(db_column='FechaPrevista')),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
    ]
